### ISSUE TITLE
[Feature Request] Jump to the next/previous same text patterns

### ISSUE THREAD

**Issue by afeblot** [ryu1kn/vscode-text-marker#14]
Hi,
I'd love to see those functions added to your extension:
- textmarker.highlightAndJump.next
- textmarker.highlightAndJump.previous

They would highlight based on current settings (CaseSensitivity and WholeMatch), then jump to the next or previous highlighted occurrence. A second call to the function would not need to highlight anything more (it would be idempotent regarding highlighting) but would just jump to the 3rd occurrence, and so on.

**Comment by ryu1kn** [comment]
Hi @afeblot , jumping to the next or previous match sounds a great idea to me! 👍

I wonder if highlight and jump should be separate commands so that you can jump to the regex patters as well.

**Comment by afeblot** [comment]
Well, you could indeed also add functions to just jump to the next/previous highlighted occurrence.
But I'd be very sad if you did not implement the joined highlight+jump functions I proposed: That would force to always use 2 different keyboard shortcuts instead of one. When your usual workflow relies on this feature (as it used to be for me with my previous editor), it is a real pain.

**Comment by ryu1kn** [comment]
Ok, then I'm thinking to go like this.

* If you execute jump to next command on a highlight, you'll jump to the next same colour highlight.
* If you execute jump to next command **not** on a highlight, you'll highlight the text beneath your cursor and then jump to the next same colour highlight.
* Same goes for the jump to previous.

**Comment by afeblot** [comment]
That looks perfect, thanks a lot!
I can't wait to see it implemented :-)

**Comment by ryu1kn** [comment]
Published as v1.4.0! 🎉

@afeblot Can you see if you're happy with it? Sorry it took me a while to work on it 😉

**Comment by afeblot** [comment]
Hi,
yes, I'm totally happy, thanks a lot :-D

**Comment by ryu1kn** [comment]
When the cursor jumps to a highlight that is outside of current visible area, the window should auto-scroll to the cursor position. I'll create a separate issue for it.
