### ISSUE TITLE
[Suggestion] - Change default color when highlight color list exhausted.

### ISSUE THREAD

**Issue by diogotrajanozup** [ryu1kn/vscode-text-marker#16]
This extension is useful! It's possible change default color gray hightlight color? Because, when select 
commented text and using dark theme, it is not possible see the highlighted text.

**Comment by ryu1kn** [comment]
Hi @diogotrajanozup , thanks for the suggestion.

If I make the default highlight colour configurable, would it work for you?

**Comment by ryu1kn** [comment]
Wow, that looks terrible... Yeah, I can clearly see the needs for the configuration. Thank you very much for posting the screenshot, they're always helpful!!

**Comment by ryu1kn** [comment]
Released as v1.1.0 :tada:

**Comment by diogotrajanozup** [comment]
It's solved! Thanks!
