### ISSUE TITLE
Toggle does not work well when it is already marked and selected

### ISSUE THREAD

**Issue by jaaviercr** [ryu1kn/vscode-text-marker#18]
Toggle does not work well when it is already marked and selected, steps to reproduce it:

1. Select some text
2. Toogle highlight
3. Without loosing selection, toogle highlight again

I think that the correct behaviour would be that the highlight should be cleared but now it does nothing.

Thank you and congratulations for this cool tool 🥇

**Comment by ryu1kn** [comment]
Thanks @jaaviercr , I could reproduce it. Thanks for reporting it!!

Text Marker: v1.1.0
VS Code: v1.24.0
macOS: 10.13.5

**Comment by ryan-surrey** [comment]
Any idea of when a fix for this will land?

I've just come across this extension, firstly let me state that its great, i love it, apart from this defect which forces me to have two key bindings to be able to quickly toggle highlighting.

Using v1.3.0

**Comment by ryu1kn** [comment]
Thanks @ryan-surrey for the encouraging comment, also the information how it's affecting your workflow. I'm a bit busy at the moment but hope that I can look into it this weekend 👍

**Comment by ryu1kn** [comment]
The fix released as v1.3.1. @jaaviercr @ryan-surrey it would be great if you could confirm it's working fine for you 😉

**Comment by jaaviercr** [comment]
@ryu1kn It works perfect now! Thank you very much! 😄

**Comment by ryu1kn** [comment]
Cool! Thanks for confirming @jaaviercr 👍
