### ISSUE TITLE
Suggestion: Don't mark when text selected

### ISSUE THREAD

**Issue by Bill-Stewart** [ryu1kn/vscode-text-marker#2]
This extension is useful! If I select something and mark, then go back and select it again, I can't see the selection. Is there a way to make the selection visible even though something is marked?

**Comment by ryu1kn** [comment]
Thanks for the suggestion. It looks like TextMarkers highlight is stronger than editor's text selection highlight.

It's nice both a selection and a marker are recognisable at the same time though I'm not too sure if this is a big concern.

Anyway, possible options I can think of right now are:

* Make the way to mark texts configurable. Right now decoration is always by changing `background-color`
  * **cons:** Only solves the problem for users ok with using non- `background-color` change highlight
* Temporarily unmark a part of text that is already marked
  * **cons:** Not too sure how it goes. Logic will become complex.

**Comment by Bill-Stewart** [comment]
Yes, it is low priority and not a very big issue.

**Comment by ryu1kn** [comment]
I recently noticed if you specify an opacity when you set a colour for highlight (like `rgba(0, 0, 255, 0.3)`), then selection will become more visible. But with this way, you've got to give opacity for all colours.

With the configuration introduced in #23 , you can give a default opacity and it will be used unless you specify an opacity for a colour! If you're still using the extension, please try it out :wink:
