### ISSUE TITLE
 Can support hidden display of menus?

### ISSUE THREAD

**Issue by tiansin** [ryu1kn/vscode-text-marker#21]
Can you add to the display and hide of the menu,I think my editor menu can't keep up.Thanks.

like: vscode-partial-diff

**Comment by ryu1kn** [comment]
Sure I can. Are you also using Partial Diff?? Thank you!!

**Comment by tiansin** [comment]
Yes, I really like these two plugins, it makes my work efficiency greatly improved, thank you for your efforts!

**Comment by ryu1kn** [comment]
Thanks for the very encouraging comment ;) I'm hoping to do the menu change tonight 👍

**Comment by ryu1kn** [comment]
Released as v1.6.0 🎉

**Comment by tiansin** [comment]
I have upgraded to the latest version, thank you very much.
