### ISSUE TITLE
Add ability to change highlight color

### ISSUE THREAD

**Issue by RobertasStrazd** [ryu1kn/vscode-text-marker#22]
How I think the process of manually selecting highlighting color should be:
Select code and right click -> Toggle highlight -> Select highlight and right click -> Update color -> RGB color picker.
or
Select code and right click -> Toggle highlight -> RGB color picker.

Love this tool, keep up the good work.

**Comment by ryu1kn** [comment]
Thanks @RobertasStrazd for the suggestion. How about this flow?

> Select code and right click -> Toggle highlight -> Select highlight and right click ->

then, `Update highlight` ➡️`Update colour` ➡️Enter colour

This way, we can utilise the command `Update highlight` which is natural points to start this colour update operation.

**Comment by ryu1kn** [comment]
Released as v1.8.0! @RobertasStrazd it would be great if you can let me know if you're happy with the functionality :wink:

**Comment by RobertasStrazd** [comment]
Just now had opportunity to test it. Perfect!
