### ISSUE TITLE
Add ability to save specific highlight color

### ISSUE THREAD

**Issue by eCustic** [ryu1kn/vscode-text-marker#24]
Changing a highlight color using `Update Highlight -> Update Color` only changes the color for that session, as it is not written down in the `settings.json` (neither `Workspace` nor `Global`). 

I suggest adding a `color` property in the `settings.json` for each highlight.

**Comment by ryu1kn** [comment]
Thanks @eCustic, i agree, that’s probably a natural evolution.

**Comment by ryu1kn** [comment]
Thanks to @BoruiGu , this feature is introduced in v1.10!
