### ISSUE TITLE
Add ability to highlight text without matching

### ISSUE THREAD

**Issue by dkchandler33** [ryu1kn/vscode-text-marker#27]
Add ability to highlight text without matching all other words.  Like if you were using a highlighter on paper.

**Comment by ryu1kn** [comment]
Hi @dkchandler33 , thanks for your suggestion!

As the core idea of Text Marker is actually highlighting all the texts that have the same pattern, I wonder if this feature may be better as a separate extension 🤔 What use case do you have in your mind?

**Comment by dkchandler33** [comment]
Several of us use VS code to take notes, just a text file.  It is nice to have the notes open in the same IDE as the code, and it would be cool to be able to highlight certain parts of the notes. I keep a text file open in the IDE that has code snippets, and other code related notes.  But, you are right, maybe this is a case for a different extension.

**Comment by ryu1kn** [comment]
Sorry for my slow response @dkchandler33 , and thanks for sharing the background!!

I'm going to close this for now. If we have more people thinking this feature should actually be covered by this extension (provided that there are other reasons we haven't talked above), we can reopen this issue 😉
