### ISSUE TITLE
It does not highlight on startup even if they are saved in Global or Workspace

### ISSUE THREAD

**Issue by 5argon** [ryu1kn/vscode-text-marker#29]
The saved regex and words are there, but when reopening the editor the highlights are not applied. Is there any way to force highlight eveything again ("refresh" ?)

**Comment by ryu1kn** [comment]
Oh ok... please report it again when you could reproduce. Thank you very much for trying to provide the video though, I know that would be incredibly helpful.

Also, there is no "re-apply" feature; so you need to reload the editor at the moment 😶
