### ISSUE TITLE
Suggestion: Use current word if nothing selected

### ISSUE THREAD

**Issue by Bill-Stewart** [ryu1kn/vscode-text-marker#3]
It would be nice if mark used current word for if nothing selected for mark/unmark. Thanks!

**Comment by ryu1kn** [comment]
This sounds good. It should be reasonable to assume that a user wants to highlight a word if a cursor is on it and nothing is selected. Thanks for the suggestion :)

**Comment by ryu1kn** [comment]
Published as v0.3.0 😃
