### ISSUE TITLE
Suggestion: unhighlight the words or text that  I  just focus, do not dispaly a words list to select

### ISSUE THREAD

**Issue by sky92zwq** [ryu1kn/vscode-text-marker#34]
Suggestion: unhighlight the words or text that  I  just focus, do not dispaly a words list to select
Thank you for your extension,  and I haven't find another extension more powerful than this.

**Comment by sky92zwq** [comment]
I'm Sorry, press "Toggle Hightlight" again ,   then the word will be unhighlighted. 
already  have this feature ...

**Comment by ryu1kn** [comment]
Hi @sky92zwq , glad that “Toggle Highlight” is what you wanted! It was actually an user suggestion; so suggestions are always welcome! 👍
