### ISSUE TITLE
Suggestion: Show matches on a scroll bar (like ctrl+f does)

### ISSUE THREAD

**Issue by mdonatas** [ryu1kn/vscode-text-marker#4]
In long files you still have to scroll to see the matches or to even know if there are any, putting them on a scroll bar would help a lot in these cases.

**Comment by ryu1kn** [comment]
Sounds good. That will be helpful. Thanks for the suggestion :)

**Comment by ryu1kn** [comment]
Published as v0.2.0 😉

**Comment by mdonatas** [comment]
Wow this was unexpectedly fast! Thank you very much for this 👍
