### ISSUE TITLE
Highlight on select

### ISSUE THREAD

**Issue by kenijo** [ryu1kn/vscode-text-marker#41]
Could you had the option to highlight on mouse select? And remove highlight when selection is unselected.

**Comment by ryu1kn** [comment]
Hi @kenijo , I’m not sure what you’re after. Isn’t that behaviour natively given by Code??

**Comment by ryu1kn** [comment]
Ah... I see. Code highlights the same pattern (not regex pattern match) in just the current active file but not **ALL** files, and that's what you're after, isn't it?

Do you want to provide a bit more context? ⬇️Doesn't need to be long 😉 

> A couple of requests from me when you raise an github issue.
> 
> * **Requesting a feature:** Please try to provide the context of why you want the feature. Such as, in what situation the feature could help you and how, or how the lack of the feature is causing an inconvenience to you. I can't think of introducing it until I understand how it helps you 🙂

**Comment by ryu1kn** [comment]
Thanks @kenijo for the clarification :+1:

Text Marker highlights patterns in all panels (both active & inactive) but not "files", I used that expression to make it intuitive, but it seems it just caused confusion, sorry 😛

I'm not sure how to trigger the toggle command by just double-clicking a word, but being able to toggle a highlight with a quicker action would be great. Thanks for the suggestion.

**Comment by lonix1** [comment]
+1!

Until [this feature](https://github.com/microsoft/vscode/issues/87274) is supported by vscode (if ever), it would be nice to have it in this extension.

i.e.: click to highlight word in all editors (of the same file).

**Comment by kenijo** [comment]
As far as I understand, this now a VS Code feature under the option:

- "editor.occurrencesHighlight": "off"
- "editor.occurrencesHighlight": "singleFile"
- "editor.occurrencesHighlight": "multiFile"
