### ISSUE TITLE
feature to clear all the highlighted texts

### ISSUE THREAD

**Issue by seyeeet** [ryu1kn/vscode-text-marker#67]
thanks for the cool plugin.
it is missing an option to clear all the highlighted texts all together :)

**Comment by ryu1kn** [comment]
Is "Clear All Highlights" what you're after?

> * Clear All Highlights (**Command ID**: `textmarker.clearAllHighlight`)
> 
>   Clear all highlights with one shot.

https://github.com/ryu1kn/vscode-text-marker#commands
