### ISSUE TITLE
Suggestion: add an option to select only full words

### ISSUE THREAD

**Issue by naufraghi** [ryu1kn/vscode-text-marker#7]
I used a lot a VIM extension ([Mark by Ingo Karkat ](http://www.vim.org/scripts/script.php?script_id=2666)) like this during refactorings or code exploration, the main difference I spot is that usually if I'm searching for `some_variable` I may or may not need to see `awe[some_variable]` highlighted.

Do you think is it possible to make this an option, or add a command one can chose to use this different behaviour?

**Comment by ryu1kn** [comment]
Thanks for the suggestion. I actually like the idea.
Just need to decide how to provide that behaviour. Also probably need to think about case sensitivity together. As you know, right now it's case sensitive and not whole word match.

Hmm...

**Comment by ryu1kn** [comment]
Just published as v0.7.0.

I'm going to add a button on status bar to toggle the mode for whole/partial match next

**Comment by ryu1kn** [comment]
Published as v0.8.0, done! Thank you for your suggestion 😉
