### ISSUE TITLE
Textmarker: Highlight Colors

### ISSUE THREAD

**Issue by jmcombs** [ryu1kn/vscode-text-marker#74]
I am interested in where you are obtaining your list of colors for highlight colors? I would like to change/add to the list of colors using names, like you are using. For example: Boysenberry or Blue Violet.

**Comment by LimChorngUan** [comment]
You can find the colour keywords here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_keywords
You can use hex or rgb too, I'm using "#445d63d3" for example

**Comment by jmcombs** [comment]
Thank you @LimChorngUan!
