### ISSUE TITLE
Single Highlighting

### ISSUE THREAD

**Issue by pacmegaman** [ryu1kn/vscode-text-marker#81]
Hi,

Totally a noob in VS code. I want to use it for plain text highlighting. But i ran into some problems. How i can highlight one sentence? If i highlighting something it highlighting sames words and sentence it annoys me , i don't need that, i need single highlighting. I googled a lot but i cannot find the solution in Vscode or your extension.

**Comment by ryu1kn** [comment]
Hi @pacmegaman 👋 Sorry that you had to google it a lot. This extension doesn't support that use-case and it's requested in #80. I'm closing this issue as a duplicate.

Please feel free to reopen this if you're after something different 🙏
