### ISSUE TITLE
parameter textmarker.clearAllHighlight unknown in user settings ?

### ISSUE THREAD

**Issue by arniol** [ryu1kn/vscode-text-marker#9]
Hello, 
The parameter textmarker.clearAllHighLight is indicated as unknown in my user settings file when I write it ?

Message = unknown configuration setting

**Comment by ryu1kn** [comment]
Hi @arniol , `clearAllHighlight` is not a configuration but a command. TextMarker at the moment has only 2 commands namely `textmarker.highlightColors` and `textmarker.delayForRefreshingHighlight`.

**Comment by arniol** [comment]
Hi !
Thanks a lot for your quick reply. Sorry, I am starting to use VS Code.
How to launch this command ?
I have tried in terminal window but this message appears : 
_'clearAllHighlight' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes_

**Comment by ryu1kn** [comment]
Oh, I see. If you're using mac, navigate the menu `View -> Command Palette...` (or hit `Cmd + Shift + P`) and search the command by typing its name `clear all highlights`. Once you find the command, just select it and it will get executed. On Windows or Linux, the keyboard shortcut may be `Ctrl + Shift + P`.

If you find yourself often using the `clear all highlights` command, you can assign keyboard shortcut to it. In that case, this vscode page would be helpful: https://code.visualstudio.com/docs/getstarted/keybindings#_customizing-shortcuts
Command IDs are on [README](https://github.com/ryu1kn/vscode-text-marker/blob/master/README.md) page of this extension.

> 'clearAllHighlight' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes

Erm... I can't read this 😅

**Comment by ryu1kn** [comment]
Closing this off. Let me know if you need more help
